### PR TITLE
Adding script for log rotation.  

### PR DESCRIPTION
**Pull request by b-long**
@dtenenba Please review and test on OSX at your convenience.

### CODE REVIEW

**Comment by dtenenba** [comment]
@b-long Looks good, a few minor things. 

* We really only care if the build has finished on the current node. So we don't need to fail if 
  the build is not finished on any other node.
* Don't hardcode the bioconductor version (3.2 in this case) into the script. Assume that it will be set
  in the environment variable `BBS_BIOC_VERSION`. 
* If we are rotating monthly, then would it make sense for the archived logs to be called e.g.
  `linux1.bioconductor.org.log.sept-2015.gz`? In other words, the name could indicate the month but not a specific date in the month.

Thanks,
Dan

**Comment by b-long** [comment]
Thanks for the feedback!  I'll get working on fixing the bugs you highlighted and push a new commit ASAP.

**Comment by b-long** [comment]
@dtenenba Fixed the issues you identified, let me know what you think.

**Comment by dtenenba** [comment]
@b-long On Macs, the home directory is /Users/biocbuild, not /home/biocbuild. Can you use $HOME instead of hardcoding it?

**Comment by b-long** [comment]
@dtenenba Absolutely, great catch.  Bug is now fixed.

**Comment by dtenenba** [comment]
So I was thinking that this would be invoked by crontab on the first day of the month at some point in the afternoon when the builds should be done (i.e nobody writing to the log). 
I will test this on the macs but I'll make a backup of the existing log because we don't REALLY want to rotate until the 1st, correct?

**Comment by b-long** [comment]
I think you're right it'd be better to run it always on the first.  We need to add the entries into the crontab for both the Mac and Linux build boxes.

**Pull request merged**
