### PR TITLE
Add _R_CHECK_SUGGESTS_ONLY_=true to Renviron.bioc

### LINKED ISSUE #248: WISH: Check with `_R_CHECK_SUGGESTS_ONLY_=true` to identify missing package dependencies
(This replaces invalid feature requests #242, #243, and #244.)

# Background

Using `_R_CHECK_SUGGESTS_ONLY_=true` will run `R CMD check` with sandboxed an R library, where on declared package dependencies in `DESCRIPTION` + recursive hard dependencies are included.  If an example, package test, or a vignette needs a package that is not in this set of dependencies, it will not be available to be loaded and result in an error.

# Wish

Add `_R_CHECK_SUGGESTS_ONLY_=true` to `Renviron.bioc` to detect missing package dependencies.

`R CMD check` sets up a sandboxed R library for it's life span.  It [uses symbolic file links to do this](https://github.com/wch/r-source/blob/8bf881e5da4da60f3aaad1b1812924817906bb29/src/library/tools/R/check.R#L138-L277), so the performance overhead for doing this is really small.  I could _not_ detect a performance penalty (see below for details).

# Examples

I ran the following examples using `Renviron.bioc` for Bioconductor 3.17:

```sh
wget https://raw.githubusercontent.com/Bioconductor/BBS/master/3.17/Renviron.bioc
```

I also ran with:

```sh
export _R_CHECK_TESTS_NLINES_=17
```

to make it clear what one of the ERRORs is about.

## Example 1: Package bnem (missing RUnit for tests and BiocStyle for vignettes)

Downloading [**bnem**](https://bioconductor.org/packages/devel/bioc/html/bnem.html) package source tarball:

```sh
$ wget https://bioconductor.org/packages/devel/bioc/src/contrib/bnem_1.7.0.tar.gz
```

### Current Bioconductor 3.17 checks

When checking with:

```sh
$ R_CHECK_ENVIRON=Renviron.bioc R --vanilla CMD check bnem_1.7.0.tar.gz
```

package passes with a single NOTE.

<details>
<pre>
* using log directory ‘/tmp/bioc/bnem.Rcheck’
* using R Under development (unstable) (2022-11-30 r83391)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘bnem/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘bnem’ version ‘1.7.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘bnem’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘rmarkdown’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘runTests.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘bnem.rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
See
  ‘/tmp/bioc/bnem.Rcheck/00check.log’
for details.
</pre>
</details>

### With also `_R_CHECK_SUGGESTS_ONLY_=true`

When checking with:

```sh
$ _R_CHECK_SUGGESTS_ONLY_=true R_CHECK_ENVIRON=Renviron.bioc R --vanilla CMD check bnem_1.7.0.tar.gz
```

the package fails with two ERRORs:

```
* checking tests ...
  Running ‘runTests.R’
 ERROR
Running the tests in ‘tests/runTests.R’ failed.
Complete output:
  > BiocGenerics:::testPackage("bnem")
  Error in library("RUnit", quietly = TRUE) : 
    there is no package called 'RUnit'
```

and

```
* checking re-building of vignette outputs ... ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘bnem.rmd’ using rmarkdown
Error: processing vignette 'bnem.rmd' failed with diagnostics:
there is no package called ‘BiocStyle’
```

<details>
<pre>
* using log directory ‘/tmp/bioc2/bnem.Rcheck’
* using R Under development (unstable) (2022-11-30 r83391)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘bnem/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘bnem’ version ‘1.7.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘bnem’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘rmarkdown’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘runTests.R’
 ERROR
Running the tests in ‘tests/runTests.R’ failed.
Complete output:
  > BiocGenerics:::testPackage("bnem")
  Error in library("RUnit", quietly = TRUE) : 
    there is no package called 'RUnit'
  Calls: <Anonymous> -> library
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘bnem.rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘bnem.rmd’ using rmarkdown
Error: processing vignette 'bnem.rmd' failed with diagnostics:
there is no package called ‘BiocStyle’
--- failed re-building ‘bnem.rmd’

SUMMARY: processing the following file failed:
  ‘bnem.rmd’

Error: Vignette re-building failed.
Execution halted

* checking PDF version of manual ... OK
* DONE

Status: 2 ERRORs, 1 NOTE
See
  ‘/tmp/bioc2/bnem.Rcheck/00check.log’
for details.
</pre>
</details>

The problem is that **bnem** is missing:

```
Suggests: RUnit, BiocStyle
```

## Example 2: Package tradeSeq (missing DelayedMatrixStats for examples and tests)

Downloading [**tradeSeq**](https://bioconductor.org/packages/devel/bioc/html/tradeSeq.html) package source tarball:

```sh
$ wget https://bioconductor.org/packages/devel/bioc/src/contrib/tradeSeq_1.13.0.tar.gz
```

### Current Bioconductor 3.17 checks

When checking with:

```sh
$ R_CHECK_ENVIRON=Renviron.bioc R --vanilla CMD check tradeSeq_1.13.0.tar.gz
```

package passes with three NOTEs.

<details>
<pre>
$ R_CHECK_ENVIRON=Renviron.bioc R --vanilla CMD check tradeSeq_1.13.0.tar.gz
* using log directory ‘/tmp/bioc/tradeSeq.Rcheck’
* using R Under development (unstable) (2022-11-30 r83391)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘tradeSeq/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘tradeSeq’ version ‘1.13.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘tradeSeq’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is  7.5Mb
  sub-directories of 1Mb or more:
    doc   6.5Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘Biobase’ ‘igraph’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
.earlyDETest: no visible binding for global variable ‘X1’
.earlyDETest: no visible binding for global variable ‘X2’
.findKnots: no visible binding for global variable ‘t1’
.findKnots: no visible binding for global variable ‘l1’
.plotGeneCount: no visible binding for global variable ‘dim1’
.plotGeneCount: no visible binding for global variable ‘dim2’
.plotSmoothers: no visible binding for global variable ‘time’
.plotSmoothers: no visible binding for global variable ‘gene_count’
.plotSmoothers: no visible binding for global variable ‘lineage’
.plotSmoothers_conditions: no visible binding for global variable
  ‘time’
.plotSmoothers_conditions: no visible binding for global variable
  ‘gene_count’
.plotSmoothers_conditions: no visible binding for global variable
  ‘lineage’
.plotSmoothers_conditions: no visible binding for global variable
  ‘pCol’
.plotSmoothers_sce: no visible binding for global variable ‘time’
.plotSmoothers_sce: no visible binding for global variable ‘gene_count’
.plotSmoothers_sce: no visible binding for global variable ‘lineage’
.plotSmoothers_sce: no visible binding for global variable ‘pCol’
Undefined global functions or variables:
  X1 X2 dim1 dim2 gene_count l1 lineage pCol t1 time
Consider adding
  importFrom("stats", "time")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘Monocle.Rmd’ using ‘UTF-8’... OK
  ‘fitGAM.Rmd’ using ‘UTF-8’... OK
  ‘multipleConditions.Rmd’ using ‘UTF-8’... OK
  ‘tradeSeq.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 3 NOTEs
See
  ‘/tmp/bioc/tradeSeq.Rcheck/00check.log’
for details.
</pre>
</details>

### With also `_R_CHECK_SUGGESTS_ONLY_=true`

When checking with:

```sh
$ _R_CHECK_SUGGESTS_ONLY_=true R_CHECK_ENVIRON=Renviron.bioc R --vanilla CMD check tradeSeq_1.13.0.tar.gz
```

the package fails with two ERRORs:

```
* checking examples ... ERROR
Running examples in ‘tradeSeq-Ex.R’ failed
...
> lin <- getLineages(rd, clusterLabels = cl, start.clus = 4)
Error in loadNamespace(x) : 
  there is no package called ‘DelayedMatrixStats’
Calls: getLineages ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

and

```
* checking tests ...
  Running ‘testthat.R’ 
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 17 lines of output:
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('testConditions.R:23'): (code run outside of `test_that()`) ──────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'DelayedMatrixStats'
Backtrace:
    ▆
 1. ├─slingshot::as.PseudotimeOrdering(sds) at testConditions.R:23:0
 2. ├─slingshot::as.PseudotimeOrdering(sds)
 3. │ └─slingshot (local) .local(x, ...)
 4. │   └─TrajectoryUtils::rowmean(reducedDim(sds), slingClusterLabels(sds))
 5. │     └─TrajectoryUtils:::.rowstats_w(...)
 6. └─base::loadNamespace(x)
 7.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 8.     └─base (local) withOneRestart(expr, restarts[[1L]])
 9.       └─base (local) doWithOneRestart(return(expr), restart)

[ FAIL 1 | WARN 1 | SKIP 0 | PASS 136 ]
```

<details>
<pre>
* using log directory ‘/tmp/bioc2/tradeSeq.Rcheck’
* using R Under development (unstable) (2022-11-30 r83391)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘tradeSeq/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘tradeSeq’ version ‘1.13.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘tradeSeq’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is  7.5Mb
  sub-directories of 1Mb or more:
    doc   6.5Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘Biobase’ ‘igraph’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
.earlyDETest: no visible binding for global variable ‘X1’
.earlyDETest: no visible binding for global variable ‘X2’
.findKnots: no visible binding for global variable ‘t1’
.findKnots: no visible binding for global variable ‘l1’
.plotGeneCount: no visible binding for global variable ‘dim1’
.plotGeneCount: no visible binding for global variable ‘dim2’
.plotSmoothers: no visible binding for global variable ‘time’
.plotSmoothers: no visible binding for global variable ‘gene_count’
.plotSmoothers: no visible binding for global variable ‘lineage’
.plotSmoothers_conditions: no visible binding for global variable
  ‘time’
.plotSmoothers_conditions: no visible binding for global variable
  ‘gene_count’
.plotSmoothers_conditions: no visible binding for global variable
  ‘lineage’
.plotSmoothers_conditions: no visible binding for global variable
  ‘pCol’
.plotSmoothers_sce: no visible binding for global variable ‘time’
.plotSmoothers_sce: no visible binding for global variable ‘gene_count’
.plotSmoothers_sce: no visible binding for global variable ‘lineage’
.plotSmoothers_sce: no visible binding for global variable ‘pCol’
Undefined global functions or variables:
  X1 X2 dim1 dim2 gene_count l1 lineage pCol t1 time
Consider adding
  importFrom("stats", "time")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... ERROR
Running examples in ‘tradeSeq-Ex.R’ failed
The error most likely occurred in:

> ### Name: plotGeneCount
> ### Title: Plot gene expression in reduced dimension.
> ### Aliases: plotGeneCount plotGeneCount,SlingshotDataSet-method
> ###   plotGeneCount,PseudotimeOrdering-method
> ###   plotGeneCount,SingleCellExperiment-method
> 
> ### ** Examples
> 
> set.seed(97)
> library(slingshot)
Loading required package: princurve
Loading required package: TrajectoryUtils
Loading required package: SingleCellExperiment
Loading required package: SummarizedExperiment
Loading required package: MatrixGenerics
Loading required package: matrixStats

Attaching package: ‘MatrixGenerics’

The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars

Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    Filter, Find, Map, Position, Reduce, anyDuplicated, aperm, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following objects are masked from ‘package:base’:

    I, expand.grid, unname

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Attaching package: ‘Biobase’

The following object is masked from ‘package:MatrixGenerics’:

    rowMedians

The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

> data(crv, package="tradeSeq")
> data(countMatrix, package="tradeSeq")
> rd <- slingReducedDim(crv)
> cl <- kmeans(rd, centers = 7)$cluster
> lin <- getLineages(rd, clusterLabels = cl, start.clus = 4)
Error in loadNamespace(x) : 
  there is no package called ‘DelayedMatrixStats’
Calls: getLineages ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ 
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 17 lines of output:
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error ('testConditions.R:23'): (code run outside of `test_that()`) ──────────
  <packageNotFoundError/error/condition>
  Error in `loadNamespace(x)`: there is no package called 'DelayedMatrixStats'
  Backtrace:
      ▆
   1. ├─slingshot::as.PseudotimeOrdering(sds) at testConditions.R:23:0
   2. ├─slingshot::as.PseudotimeOrdering(sds)
   3. │ └─slingshot (local) .local(x, ...)
   4. │   └─TrajectoryUtils::rowmean(reducedDim(sds), slingClusterLabels(sds))
   5. │     └─TrajectoryUtils:::.rowstats_w(...)
   6. └─base::loadNamespace(x)
   7.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
   8.     └─base (local) withOneRestart(expr, restarts[[1L]])
   9.       └─base (local) doWithOneRestart(return(expr), restart)
  
  [ FAIL 1 | WARN 1 | SKIP 0 | PASS 136 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘Monocle.Rmd’ using ‘UTF-8’... OK
  ‘fitGAM.Rmd’ using ‘UTF-8’... OK
  ‘multipleConditions.Rmd’ using ‘UTF-8’... OK
  ‘tradeSeq.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 2 ERRORs, 3 NOTEs
See
  ‘/tmp/bioc2/tradeSeq.Rcheck/00check.log’
for details.
</pre>
</details>

The problem is that **tradeSeq** is missing:

```
Suggests: DelayedMatrixStats
```

# Performance overhead

Running `R CMD check` with and without `_R_CHECK_SUGGESTS_ONLY_=true` on **[progressr](https://cran.r-project.org/package=progressr)**, which is an all OK package with lots of Suggests:ed dependencies that are also "heavy", confirms that there should be little, near-zero, overhead added.

With:

```sh
$ _R_CHECK_SUGGESTS_ONLY_=true R_CHECK_ENVIRON=Renviron.bioc command time R --vanilla CMD check progressr_0.11.0.tar.gz
...
Status: OK

94.37user 9.24system 2:52.30elapsed 60%CPU (0avgtext+0avgdata 135824maxresident)k
19768inputs+21888outputs (38major+1897963minor)pagefaults 0swaps
```

Without:

```sh
$ R_CHECK_ENVIRON=Renviron.bioc command time R --vanilla CMD check progressr_0.11.0.tar.gz
...
Status: OK

94.58user 9.57system 2:56.51elapsed 59%CPU (0avgtext+0avgdata 136000maxresident)k
0inputs+21960outputs (0major+1898301minor)pagefaults 0swaps
```

### PR DESCRIPTION
**Pull request by jwokaty**
Added to the Renviron.bioc of 3.16 and 3.17. Wait until we check the 3.17 build report as R devel was updated on the 3.17 machines 2022/12/1.

Close #248

### CODE REVIEW

**Comment by hpages** [comment]
Not for the 3.16 builds please, unless we want to introduce a blood bath on the release build reports :wink: See https://github.com/Bioconductor/BBS/issues/248#issuecomment-1334239132

**Comment by hpages** [comment]
Thanks for adding the long comment to Renviron.bioc :wink: 

What about this:

> To make the need for this particular setup more prominant and help with reproducibility of the CHECK results on Linux, we could also edit the dotted box displayed at the beginning of each individual report. See for example the "To the developers/maintainers of the Biobase package:" box on [this report](https://bioconductor.org/checkResults/3.17/bioc-LATEST/Biobase/nebbiolo1-checksrc.html) (i.e. the box that is right below the title of the report "CHECK results for Biobase on nebbiolo1").

Any opinion on that?

Thanks again.

**Comment by jwokaty** [comment]
Can you explain your suggestion more? This sounded like a suggestion but it wasn't clear if it is just to make the last line more prominent in some way.

I might reword/shorten/format as

```
Changes take upto 48 hours to appear on build reports.
See [Troubleshooting Build Reports](https://contributions.bioconductor.org/troubleshooting-build-report.html) and use [Renviron.bioc](https://bioconductor.org/checkResults/3.17/bioc-LATEST/Renviron.bioc) to troubleshoot errors reported on this page.
```

Or do you mean we should put temporary messaging specifically about the error?

```
Have a new missing package dependency? We recently updated our [Renviron.bioc](https://bioconductor.org/checkResults/3.17/bioc-LATEST/Renviron.bioc) to detect dependencies missing from Suggests. 
```

**Comment by hpages** [comment]
This was indeed a suggestion, and a pretty vague one, sorry. Was not sure if you saw it. I was thinking of adding something like this:
```
- If 'R CMD check' started to fail recently on the Linux builder complaining that a dependency is
  missing, it's likely because that dependency is not listed in the Suggests field of your package.
  See _R_CHECK_SUGGESTS_ONLY_=true setting in <A href="../Renviron.bioc">Renviron.bioc</A>
  for how to reproduce this error.
```
We don't necessarily need to keep this forever but it might help in the context of the upcoming release.

**Comment by jwokaty** [comment]
I added a note but did a little rewording, added extra BRs, and removed the center alignment, which I find hard to read.

**Comment by hpages** [comment]
sounds good

**Pull request merged**
