### PR TITLE
Replace problematic references to Python modules

### LINKED ISSUE #224: Clean up mac doc edits for python
Thank you. Looks like you're missing the triple backtick after `R CMD build destiny`.

        Also, for the sake of clarity, can we simplify the terminology and stick with "Python modules"? Right now the doc uses 3 different designations for those: "Python modules", "Python packages", and "pip packages" :dizzy: 

        Thanks again

_Originally posted by @hpages in https://github.com/Bioconductor/BBS/issues/223#issuecomment-1283071139_

### PR DESCRIPTION
**Pull request by jwokaty**
I removed a lot of references to Python 'modules' as I felt they weren't really correct and replaced with libraries or packages, since that's what we're mostly talking about.

Close #224

### CODE REVIEW

**Comment by hpages** [comment]
Hmm.. I see, things are more complicated than what I thought.

The man page for `pip3` (`man pip3`) uses the term "Python package". So what we list in the `pip_pkgs.txt` and `pip_spb.txt` files are _Python packages_.

But the `import` statement in Python imports _modules_ (https://docs.python.org/3/reference/simple_stmts.html#import).

To add _Python modules_ to a system, one needs to install _Python packages_, usually via `pip`/`pip3`, and one _Python package_ can contain several _Python modules_.

What makes things a little bit confusing is that very often a _Python package_ contains a single _Python module_, and the two have the same name.

Ok, so maybe we need to live with the 2 terms, and use one or the other depending on context: _Python packages_ when showing examples of `pip` commands, and _Python modules_ when showing examples of `import` commands. And we probably don't really need to introduce terms like "Python library" or "pip module", or do we?

Sorry, I didn't mean to start a long conversation about this. Just noticed that [this PR](https://github.com/Bioconductor/BBS/pull/223/files) introduced 2 new terms, "Python package", and "pip module", in addition to the term "Python module" which has been used consistently across all the `Prepare-*-HOWTO.md` documents.

Whatever we do with this, we want to keep the terminology as simple as possible and use it consistently within and across all documents.

**Comment by jwokaty** [comment]
No worries. I can live with the language. Either way, I would do the same things that I do with Python packages, libraries, and modules. Any opposition to me merging this?

**Comment by hpages** [comment]
Well, I'm trying to make the point that we only need 2 terms and that we should be consistent within and across all `Prepare-*-HOWTO.md` documents. Do you agree with that? Does this PR achieve that?

Again, I didn't mean to start a long discussion or to make this hard on you, sorry. I just feel that the current PR doesn't really improve the situation w.r.t terminology.

**Comment by jwokaty** [comment]
If modules is what is used in the other docs, then I will use them here.

**Comment by jwokaty** [comment]
I accidentally closed this issue.

**Pull request merged**
