### PR TITLE
Fix postrun for Mac ARM64

### LINKED ISSUE #179: Propagate of M1 binaries - part 1: Make sure postrun.sh does the right thing
Hi Jen,

Since the introduction of M1 binaries the basic layout of a CRAN-style package repo now looks like this:

    ├── bin
    │   ├── macosx
    │   │   ├── big-sur-arm64             #  new
    │   │   │   └── contrib               #  new
    │   │   │       └── 4.2               #  new
    │   │   │           └── PACKAGES      #  new
    │   │   └── contrib
    │   │       └── 4.2
    │   │           └── PACKAGES
    │   └── windows
    │       └── contrib
    │           └── 4.2
    │               └── PACKAGES
    └── src
        └── contrib
            └── PACKAGES

We will need to propagate the new M1 binaries to `bin/macosx/big-sur-arm64/contrib/4.2/`.

Let's focus on `postrun.sh` for now. `postrun.sh` does basically 4 things, in this order:
- Call `BBS-make-BUILD_STATUS_DB.py` to generate the _package build status database_ (`BUILD_STATUS_DB.txt`).
- Call `BBS-make-OUTGOING.py` to create and populate the `OUTGOING` folder.
- Call `BBS-make-PROPAGATION_STATUS_DB.py` to generate the _package propagation status database_ (`PROPAGATION_STATUS_DB.txt`).
- Call `BBS-report.py` to generate the HTML report. Note that the report will display little LEDs in the rightmost column to indicate the propagation status of each package (need to switch to the "Long report" to see them).

The focus of this issue is to make sure that all these things work properly for the M1 builds, and that we end up with a report showing the LEDS.

What needs to happen (in this order):

1. Fix `BBS-make-BUILD_STATUS_DB.py`. I could be wrong but I don't think that the script works right now for the M1 builds because I believe the script expects to see the results of the CHECK stage, which we don't run for the M1 builds.

2. Choose a name for the `OUTGOING` subfolder where the `postrun.sh` script will copy the M1 binaries produced by kjohnson. The `OUTGOING` folder is on the central builder (biocbuild account on nebbiolo2), under `~/public_html/BBS/3.16/bioc/`. Right now it has the following subfolders: `source`, `win.binary`, and `mac.binary`. Note that those exact names is our internal business so they don't need to match what CRAN is using for the layout of a CRAN-style package repo or to match the official `pkgType` used by `install.packages()` and family. We use these names when we set the `BBS_OUTGOING_MAP` variable to specify what to populate the `OUTGOING` subfolders with. For example this is what we use at the moment at the end of the daily devel builds:
    ```
    export BBS_OUTGOING_MAP="source:nebbiolo2/buildsrc win.binary:palomino4/buildbin mac.binary:lconway/buildbin"
    ```
    If we choose `OUTGOING/m1.binary` for where we're going to copy the M1 binaries produced by kjohnson, then we'll need to set `BBS_OUTGOING_MAP` as follow for the `bioc-m1` builds:
    ```
    export BBS_OUTGOING_MAP="m1.binary:kjohnson/buildbin"
    ```
    Then when you run the `postrun.sh` script at the end of the `bioc-m1` builds on nebbiolo2, the M1 binaries produced by kjohnson should end up in `OUTGOING/m1.binary/`. Note that the `BBS-make-OUTGOING.py` script actually does the job (it's called by `postrun.sh`). Try to run `postrun.sh` and see how it goes.

3. In the biocpush account (on nebbiolo2): create `~/PACKAGES/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/` with empty `PACKAGES` index file in it.

4. Fix `BBS-make-PROPAGATION_STATUS_DB.py`. The script looks at the content of `OUTGOING/source`, `OUTGOING/win.binary`, and `OUTGOING/mac.binary` (and also at other things, but they don't matter here) to infer the propagation status of source, Windows, and Intel Mac packages. It doesn't know about the new `OUTGOING/m1.binary` folder so needs to be modified.

5. Try to run `postrun.sh` and see how it goes. Did `BBS-make-PROPAGATION_STATUS_DB.py` do its job? Do we see LEDs on the report?

I've probably forgotten a few things, sorry, but that should get you started. Don't hesitate to ask below. I'll update/correct/complete the above as we go. Thanks!

### PR DESCRIPTION
**Pull request by jwokaty**
Close #179

### CODE REVIEW

**Comment by jwokaty** [comment]
I had to change the name of the OUTGOING_MAP back to `mac.binary` since this is later passed to `tools::write_PACKAGES()`. Note: I am changing the name from `bioc-m1` to `bioc-mac-arm64` so the name won't be outdated. I still have the `bioc-m1` directory on nebbiolo2 and ran it on packages built along that path: https://master.bioconductor.org/checkResults/3.16/bioc-m1-LATEST/

**Comment by hpages** [comment]
> I had to change the name of the OUTGOING_MAP back to mac.binary ...

Problem with this is that it will clash with the `OTGOING/mac.binary` folder that already exists on the central builder if we decided to run the M1 builds as part of the daily builds (and we will probably want to do this at some point once we have the computing power to do so). So we need to use something different and replace it with `"mac.binary"` when we call `tools::write_PACKAGES()`.

Whatever you use you will need to use the same in this line from the `makePropagationStatusDb()` function:
```
    OUTGOING_types <- c("source", "win.binary", "mac.binary")
```
Just append the new type to the 3 existing types.

Today you have a report and all the build products are on nebbiolo2. Would it help to pause the builds so all the things you need to work on `postrun.sh` are not wiped out while you work on `postrun.sh`? Then you would resume once `postrun.sh` works.

Thanks

**Comment by jwokaty** [comment]
I thought about this when I making changes so it wasn't too hard to allow use of 'mac.binary.arm64'. I am testing this on the 'bioc-m1' directory so I don't necessarily need to pause the regular builds. I think this is good and ready for merging.

**Comment by hpages** [comment]
> I think this is good and ready for merging.

Excellent! Please go ahead If you're confident that `postrun.sh` is working properly.

> ... so I don't necessarily need to pause the regular builds

I was not talking about pausing the "regular builds" but pausing the M1 builds :confused: The "regular builds" (a.k.a. daily builds) are completely separated from the M1 builds and pausing them wouldn't help for troubleshooting the M1 builds (it would also upset many developers so shouldn't be done lightly and without prior announcement).

OTOH if you pause the M1 builds, you can run `postrun.sh` manually on nebbiolo2 and make all the adjustments you need until it works without having to worry about the M1 build products being wiped out by the next `prerun.sh`. Sorry I just don't know how you test `postrun.sh` for the M1 builds right now. Do you have a way to test it or do you wait for the next scheduled run? The latter wouldn't be very effective since it only gives you 2 shots per week. I'm talking about an easy way for you to get an unlimited number of shots per day, 7 days a week :wink:

**Comment by hpages** [comment]
It looks like you're using `"mac.binary.arm64"` for `OUTGOING_types` in `utils/makePropagationStatusDb.R` but you're using `"mac.binary"` for `BBS_OUTGOING_MAP` in `3.16/bioc-mac-arm64/nebbiolo2/config.sh`. I'm surprised this even works.
 
In any case I feel that `"mac.arm64.binary"` would be a better name/label for these binaries. More consistent with the name of those builds and how we refer to them ("Mac arm64" builds).

**Comment by jwokaty** [comment]
Actually, that doesn't work. I forgot to update that file. Thank you!

Sorry I wasn't clear about the builds. (I think I was just happy to push my work!) I don't need to pause the mac arm64 builds because I copied `bioc-m1` (the original name) to `bioc-mac-arm64`. I was lucky in that it had finished building and sending the binaries to nebbiolo2, which is what I have been testing on with a few tweaks to match the `-m1` path. (The mac arm64 builds that should finish tomorrow will be in the `bioc-mac-arm64` directory.)

**Comment by hpages** [comment]
Got in now. Thanks for clarifying.

Any chance you can rename `mac.binary.arm64` -> `mac.arm64.binary`?

**Comment by jwokaty** [comment]
Why is that better?

**Comment by hpages** [comment]
For binary packages, we've always used the `<type-of-binary>.binary` convention. This is consistent with what the CRAN folks have done in the past e.g. at some point they were using `mac.el-capitan.binary` for binaries built for El Capitan.

**Comment by jwokaty** [comment]
I've renamed following your suggestion and will merge.

**Pull request merged**
