### PR TITLE
Add check for cross references in manual pages

### PR DESCRIPTION
**Pull request by llrs**
To avoid issues between links on manual pages there is this new environmental variable `_R_CHECK_XREFS_NOTE_MISSING_PACKAGE_ANCHORS_` 
According to the description in [R internals]( https://cran.r-project.org/doc/manuals/r-devel/R-ints.html): "If set to a true value, check whether Rd cross-references to targets not in the package itself or the base packages have package anchors."

This will help in links from the html versions of manuals created with `pkg2HTML`.

### CODE REVIEW

**Comment by jwokaty** [comment]
@hpages Ok to merge this?

**Comment by llrs** [comment]
I suggest this as CRAN is trying to provide HTML manual pages of all packages and Bioconductor could do the same. I've been talking with @vjcitn since 07/2024 about this. 

It only signals a Note (not a warning or error), and there is some work to do to completely fix cross-references handling by R (I posted about this on [R-devel mailing list](https://stat.ethz.ch/pipermail/r-devel/2024-September/083626.html)).

**Comment by hpages** [comment]
@jwokaty Yes, ok to merge this. Thanks!

**Comment by jwokaty** [comment]
Thanks for your contribution. I've deployed on all our devel builders.

**Pull request merged**
