### PR TITLE
Add .travis.yml for static analysis and appropriate build badge.

### PR DESCRIPTION
**Pull request by b-long**
Adding linting for python and some shell scripts.

### CODE REVIEW

**Comment by b-long** [comment]
cc/ @jimhester Mind giving some input on this when you get a chance?

**Comment by jimhester** [comment]
I would avoid `sudo: true` if possible, using the container based infrastructure is usually faster and allows you to cache dependencies. Shellcheck is a whitelisted package (https://github.com/travis-ci/apt-package-whitelist/blob/99e705fc93aa9dc6d4087b7be9d076c5cce6c941/ubuntu-precise#L9272) so you can install it using the [apt addon](http://docs.travis-ci.com/user/apt/), although this won't be the latest version of shellcheck (probably doesn't matter). Note you don't need sudo access to use pip, you probably just need to pass the `--user` argument.

So I would use `language: c` or `language: python` with `sudo: off`, install the shellcheck apt package and pyflake the run them. Something like (untested)

```yml
language: python
sudo: false
addons:
  apt:
    packages: 
      shellcheck
python:
  - "2.7"
cache: pip
install: pip install --user pyflakes
script:
  - shellcheck ./3.3/bioc/zin2/postrun.sh  ./3.2/bioc/zin1/postrun.sh
  - pyflakes *.py
notifications:
  email:
    - brian@bioconductor.org
```

**Comment by jimhester** [comment]
It looks like ubuntu precise is not on the default source list, I will look into the proper syntax to add it.

**Comment by jimhester** [comment]
:+1: LGTM, merge away.

**Comment by b-long** [comment]
Thanks @jimhester .  Merging & closing.

**Pull request merged**
