### PR TITLE
M1 binaries

### PR DESCRIPTION
**Pull request by jwokaty**
@hpages Could I ask you to look at these proposed changes for propagating the M1 binaries? I have not yet tested it, but it's likely I missed a lot. I plan to comment out the sections in the config file to make sure we can put it on the report first.

It's only building about 700ish packages right now, so I still have some additional work troubleshooting.

### CODE REVIEW

**Comment by hpages** [comment]
Hi Jen,

Can I suggest that we leave propagation out of the picture for now and that we focus on: (1) having kjohnson run the builds daily, then (2) have its results displayed on the report? Once this runs smoothly, we can start worrying about (3) propagation. Those are 3 separate problems and I think that tackling them separately and in this order will make things easier.

So let's focus on (1) for now.

Remember that kjohnson being a Mac mini, it won't have the computing power to run all the build stages i.e. INSTALL, BUILD, CHECK, and BUILD BIN. However, you cannot run the BUILD BIN stage alone because binary packages are built from the source tarballs (see the command used by the build system to build the Mac binary e.g. for **Biobase** [here](https://bioconductor.org/checkResults/3.16/bioc-LATEST/Biobase/lconway-buildbin.html)). This means that you also need to run the BUILD stage. But before you can run the BUILD stage, all the packages and their deps need to be installed. This is performed by the INSTALL stage.

So to produce binaries you'll need to run the INSTALL, BUILD, and BUILD BIN stages. The only stage you'll actually skip is CHECK, but this will already save A LOT of time because CHECK is by far the longest of all the stages (I think this stage alone represents more than 50% of the total build time or something like that).

So I would suggest that you try using

    $BBS_PYTHON_CMD $BBS_HOME/BBS-run.py STAGE2 STAGE3 STAGE5

on kjohnson and see how it goes (make the change locally on kjohnson, no need to commit anything for now). This is a combination of stages that we've never used before so I'm not sure what will happen. Best way to know is to try it :wink: If we get an error, then we'll dig into BBS code and make adjustments.

H.

**Comment by jwokaty** [comment]
@hpages Thanks for your comments. I am writing the code but also just making the adjustments locally on kjohnson and am in agreement with your strategy.

**Comment by hpages** [comment]
Hi Jen,

Maybe I should have been clearer. I think that instead of putting the entire work you're doing on the M1 builds in one big single PR it would be better to break your work into smaller independent units, with one PR per unit. Using smaller _incremental_ PRs that each have a narrower focus adds clarity and allows us to be more efficient. Also it makes it much easier for me to follow and provide feedback.

For example I see that this PR touches things in `BBS/propagation/3.16/` but we're not there yet (this is stuff that we'll need to discuss after we're done with "Propagate of M1 binaries - part 1").
  
Then once a PR is merged and deployed, we can start working on the next one. 

What I mean concretely is:
- Now that you have the kjohnson builds up and running (without propagation yet), I would encourage you to create a first PR for that. Then we'll merge it and deploy it (I'll be glad to take a look at if you want me to).
- Our next target is issue #179, and the short term goal is to turn this into a second PR (that we'll also merge and deploy before moving to the next one).
- And so on...

Does it make sense?

Thanks,
H.

**Comment by jwokaty** [comment]
Thanks for the clarification!

**Comment by jwokaty** [comment]
Note (to myself): Rename M1 to Mac ARM64 as M1 will be "dated" as Mac introduces more Mx chips.

**Pull request merged**
