### PR TITLE
Add note about Downloads, Downloads to tmp

### LINKED ISSUE #362: MacOS Ventura Terminal Needs Full Disk Access for Downloads
In Mojave, Mac implemented a feature to restrict disk access to applications. From Ventura, the terminal needs to be granted full disk access to access the contents of the Downloads directory for a user that has been created via the GUI. This can be observed by `ls Downloads`, which will return `Operation not permitted`. If the Downloads directory is created manually, such as for a user created via the terminal, accessing content in the Downloads directory may result in unexpected behavior.

### PR DESCRIPTION
**Pull request by jwokaty**
Close #362

### CODE REVIEW

**Comment by hpages** [comment]
@jwokaty It's important to keep the downloads around. Using `/tmp` for this means we will probably loose them at some point (the OS can do whetever it wants with `/tmp` e.g. wipe it out on reboots).
It would be better to use a place in the `biocbuild`'s home for that, maybe `~/tmp`? Thanks

**Comment by jwokaty** [comment]
I deliberately selected /tmp for that reason. If downloads are not available to users, we should really consider if that download should be used. 

Never the less, I will do as you request.

**Comment by hpages** [comment]
XQuartz is not available for users? I don't get it.

**Comment by jwokaty** [comment]
You said it is important to keep what's downloaded. I don't think it's so important; we should always be able to download what's needed and if it's not available for download (and available to users) then we shouldn't be using it.

**Comment by jwokaty** [comment]
As requested https://github.com/Bioconductor/BBS/commit/79268a5b096341136024bb8b8cfb93148629e792

**Comment by hpages** [comment]
Thanks for clarifying.

I should have explained why I thought it was important, sorry. Ok so maybe not so important but really convenient to keep at hand. Command_Line_Tools_for_Xcode, XQuartz, Java, MacTeX, Pandoc, etc... are sensitive system components. Keeping them in one place provides a snapshot of what we currently have on the machine, which helps with traceability (what was downloaded, when, and which version). Plus it makes it easy to reinstall if needed (happens sometimes), or to do detective work when things go wrong (in which case re-downloading would not necessarily be guaranteed to help fully understand "the crime scene"). Maybe that sounds a little bit paranoid but there's been a couple of situations in the past where having these things around was really helpful.

**Pull request merged**
